services:
  reamindmedatabase:
    image: mysql/mysql-server
    container_name: remindme_database
    ports:
      - 3306:3306
    volumes:
      - ./database/entrypoint:/docker-entrypoint-initdb.d
      - ./database/others:/others
      - ./database/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: I98b7z5$
        MYSQL_USER: root
        MYSQL_PASSWORD: I98b7z5$
  reamindmeapi:
    image: marcelapsilverio/reamindmeapi:1.0
    container_name: remindme_api
    expose:
      - 8080
    ports:
      - 8080
    volumes:
      - ./container:/code
    depends_on:
      reamindmedatabase:
        condition: service_started
